branch-defaults:
  default:
    environment: tryagain-dev2
    group_suffix: null
  master:
    environment: tryagain-dev2
environment-defaults:
  tryagain-dev2:
    branch: null
    repository: null
global:
  application_name: tryagain
  branch: null
  default_ec2_keyname: FirstKeyPair
  default_platform: Python 3.6
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
